### PR TITLE
Creation of a doc folder

### PR DESCRIPTION
**Pull request by LRossman**
I believe the discussions on this site would benefit by having a **doc** folder where people could post more extensive and more formal descriptions of the proposals they want to put forward for the next EPANET, compared to the rather brief space normally used for issue discussion. I have placed my EWRI EPANET Visioning Committee white paper in a sub-folder since I strongly believe it belongs somewhere on this site.

### CODE REVIEW

**Comment by jamesuber** [comment]
@LRossman I think we should all look carefully at the (new) information in the readme and the suggestions there about how to move forward.

The overriding goal to me is that the community start to collaborate on shared goals that will be addressed by the software spec. It is hard for me to respond to fully blown proposals without knowing how the dev community wants to use the next incarnation of EPANET. It’s critical that you be very involved, and equally critical that others speak up about their ideas. The latter is made harder by asking the group to digest and critically review thoughts that can appear to be fully baked. Let’s parse this into ideas that can be discussed within issues. We will have to distill those into an SRS, but I view that as a separate process. 

This goes far beyond an object orientation, which is not a goal but a development framework. 

A few example goals came out of the software arch meeting this past Monday. A great one was to formally separate the concerns of network creation and specification (and maybe also simulation output?), from the simulation numerical methods. That’s never been done and many folks believed that it would bring huge benefits. So I’d like to see a complete set of those goals plus reasonably detailed sub goals, prior to evaluating a fully formed arch proposal.

**Comment by LRossman** [comment]
Here's what the readme says:

*This project's scope is limited to* **design and development** *of a hydraulic and water quality solution engine, extended-period simulation capabilities, and I/O extensions to provide backwards compatibility with EPANET files and assets.*

*If you have* **concrete design suggestions**, *make them there, discuss, and open a PR to master with your contribution to the design documents.*

I think my white paper deals with engine "design and development", puts forth "concrete design suggestions" and therefore deserves to be discussed. Since you won't post the full paper in a place where everyone can readily access it, I will have to find another way to expose it to the community.

I really appreciate the great work you and the other maintainers of this site are doing to allow an open and free exchange of ideas for the next EPANET.

**Comment by michaelbynum** [comment]
I think that Lew's document is extremely useful here. Even though his document covers many aspects, it may spark several smaller discussions in the issues. I have read Lew's document and, once I have time, will post some comments.

**Comment by samhatchett** [comment]
Right Lew - the readme says:

The best place to get involved is in this repo's issues. If you have concrete design suggestions, make them there, discuss, and open a PR to master with your contribution to the design documents.

So let’s discuss design considerations in Issues. Once proposals have been vetted and accepted, they can be ported to the design documents.

**Comment by jamesuber** [comment]
Lew I had originally posted your document myself in the thread that led to the arch discussion meeting. It is misleading to say that there is no place to make that document available — I encourage you to open an issue here, post that document, and maybe provide a little background about how it was created if you wish. That’s what the issues are for, and I’d like to transition, now, to starting a discussion of them.

**Comment by samhatchett** [comment]
@michaelbynum I agree that the document would be extremely useful for discussion. The issue really is where and how to have that discussion. I'm taking inspiration from a hugely successful community design effort, `swift-evolution`, where proposals are discussed and debated via threaded listserv messages, and accepted proposals get pulled into the documentation. A pull request, in most open-source worlds, means that the ideas are ready to be adopted. They have been fully discussed, vetted, and agreed upon by a critical mass of interested parties.

So again, I would encourage @LRossman to please post the document as an Issue, or break up the document into manageable pieces and post them as separate Issues. Either way, the document deserves a fair and open discussion.

**Pull request closed without merging**
